(()=>{"use strict";
const yearEl=document.getElementById("yearReadout"),mapYear=document.getElementById("mapYear"),countEl=document.getElementById("mapCommunityCount"),dots=document.getElementById("mapDots"),legend=document.getElementById("mapLegend"),land=document.getElementById("mapLand");
if(!yearEl||!mapYear||!countEl||!dots||!legend||!land)return;
const periods=[{"from":-6,"to":99,"c":[["Judea / Jerusalem",31.8,35.2,5],["Antioch",36.2,36.2,3],["Asia Minor",39,32.5,3],["Rome",41.9,12.5,2]]},{"from":100,"to":312,"c":[["Rome",41.9,12.5,5],["Asia Minor",39,32.5,5],["Antioch",36.2,36.2,4],["Alexandria",31.2,29.9,4],["Levant",32,35.2,3],["North Africa",36.8,10.2,3]]},{"from":313,"to":599,"c":[["Constantinople",41,29,6],["Rome",41.9,12.5,5],["Alexandria",31.2,29.9,4],["Antioch",36.2,36.2,4],["Levant",32,35.2,4],["North Africa",36.8,10.2,3],["Ethiopia",9,40,3],["Armenia",40.2,44.5,3]]},{"from":600,"to":999,"c":[["Constantinople",41,29,6],["Rome",41.9,12.5,5],["Western Europe",48,5,5],["Eastern Mediterranean",34,34,3],["Ethiopia",9,40,3],["Armenia",40.2,44.5,3]]},{"from":1000,"to":1499,"c":[["Western Europe",48,5,6],["Constantinople",41,29,5],["Eastern Europe",50,25,4],["Ethiopia",9,40,3],["Levant",32,35.2,2]]},{"from":1500,"to":1799,"c":[["Western Europe",48,5,6],["Eastern Europe",52,25,5],["Latin America",19,-99,5],["North America",39,-77,3],["Ethiopia",9,40,3],["Philippines",14.6,121,3]]},{"from":1800,"to":1945,"c":[["Europe",50,15,6],["United States",40,-80,5],["Latin America",-10,-55,6],["Sub-Saharan Africa",0,25,3],["Philippines",14.6,121,4],["Oceania",-25,135,2]]},{"from":1946,"to":2026,"c":[["Europe",50,15,6],["United States",39,-98,6],["Latin America",-10,-55,6],["Sub-Saharan Africa",0,25,6],["Philippines",14.6,121,5],["South Korea",37.6,127,3],["Oceania",-25,135,3]]}];
function point(lat,lon){return{x:lon+180,y:90-lat}}
function ringPath(r){return r.map((c,i)=>{const p=point(c[1],c[0]);return(i?"L":"M")+p.x.toFixed(2)+" "+p.y.toFixed(2)}).join(" ")+" Z"}
function geometryPath(g){if(g.type==="Polygon")return g.coordinates.map(ringPath).join(" ");if(g.type==="MultiPolygon")return g.coordinates.flatMap(p=>p.map(ringPath)).join(" ");return""}
fetch("data/ne_110m_land.geojson").then(r=>r.json()).then(data=>{const ns="http://www.w3.org/2000/svg",frag=document.createDocumentFragment();data.features.forEach(f=>{const d=geometryPath(f.geometry);if(!d)return;const p=document.createElementNS(ns,"path");p.setAttribute("d",d);p.setAttribute("fill-rule","evenodd");frag.appendChild(p)});land.replaceChildren(frag)}).catch(()=>{});
function parseYear(){const t=yearEl.textContent.trim();const n=parseInt(t.replace(/[^0-9]/g,""),10);return Number.isFinite(n)?(/BCE/i.test(t)?-n:n):null}
let comparisonMapActive=false;
function update(){if(comparisonMapActive)return;const y=parseYear();if(y===null)return;const p=periods.find(p=>y>=p.from&&y<=p.to)||periods[periods.length-1];mapYear.textContent=y<0?Math.abs(y)+" BCE":y+" CE";countEl.textContent=p.c.length+(p.c.length===1?" center":" centers");dots.innerHTML="";legend.innerHTML="";const ns="http://www.w3.org/2000/svg";p.c.forEach(([name,lat,lon,size])=>{const q=point(lat,lon),halo=document.createElementNS(ns,"circle"),core=document.createElementNS(ns,"circle");halo.setAttribute("cx",q.x);halo.setAttribute("cy",q.y);halo.setAttribute("r",2.2+size*.72);halo.setAttribute("class","map-community");core.setAttribute("cx",q.x);core.setAttribute("cy",q.y);core.setAttribute("r",.65+size*.28);core.setAttribute("class","map-community-core");dots.append(halo,core);const item=document.createElement("span");item.textContent=name;legend.appendChild(item)})}
new MutationObserver(update).observe(yearEl,{childList:true,characterData:true,subtree:true});
update();
window.addEventListener("history-map-compare",e=>{
 comparisonMapActive=!!(e.detail&&e.detail.active);
 if(!comparisonMapActive)update();
});
})();