const events=[
  {year:570,depth:180,title:"Birth of Muhammad",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:610,depth:350,title:"First revelations to Muhammad",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:622,depth:520,title:"Hijra to Medina",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:624,depth:690,title:"Battle of Badr",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:625,depth:860,title:"Battle of Uhud",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:627,depth:1030,title:"Battle of the Trench and Banu Qurayza episode",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:630,depth:1200,title:"Muslim conquest of Mecca",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:632,depth:1370,title:"Death of Muhammad and succession crisis",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:632,depth:1540,title:"Ridda Wars",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:636,depth:1710,title:"Battle of Yarmouk",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:637,depth:1880,title:"Muslim capture of Jerusalem",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:644,depth:2050,title:"Uthman becomes third caliph",location:"Medina",story:"After Umar's assassination, Uthman ibn Affan was selected as caliph. His rule oversaw further expansion and the standardization of the Qur'anic consonantal text in Islamic tradition, but accusations of favoritism helped produce political opposition.",context:"Caliphal succession",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Caliphal succession",Evidence:"Uthman's caliphate and assassination are historical; accounts of the Qur'an's codification and political disputes are transmitted through early Muslim literary sources."},sourceStatus:"Uthman's caliphate and assassination are historical; accounts of the Qur'an's codification and political disputes are transmitted through early Muslim literary sources.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:656,depth:2220,title:"First Fitna begins",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:656,depth:2390,title:"Caliph Uthman assassinated",location:"Medina",story:"Rebels killed Uthman in Medina after mounting opposition to his government. His death shattered political consensus and immediately preceded the First Fitna.",context:"Political assassination / civil-war trigger",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Political assassination / civil-war trigger",Evidence:"The assassination is historical; later sectarian narratives differ sharply in assigning blame."},sourceStatus:"The assassination is historical; later sectarian narratives differ sharply in assigning blame.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:656,depth:2560,title:"Battle of the Camel",location:"Basra",story:"Forces aligned with Caliph Ali defeated an army associated with Aisha, Talha and al-Zubayr near Basra during the First Fitna.",context:"Muslim civil war",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Muslim civil war",Evidence:"The battle is historical. Later Sunni and Shia traditions remember its leading figures differently."},sourceStatus:"The battle is historical. Later Sunni and Shia traditions remember its leading figures differently.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:657,depth:2730,title:"Battle of Siffin",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:661,depth:2900,title:"Assassination of Ali and rise of Umayyad rule",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:680,depth:3070,title:"Battle of Karbala",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:683,depth:3240,title:"Second Fitna and siege of Mecca",location:"Mecca",story:"During renewed civil war over the Umayyad succession, Syrian forces besieged Mecca while Abd Allah ibn al-Zubayr challenged Umayyad rule. The Kaaba was damaged during fighting.",context:"Muslim civil war / sacred-site violence",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Muslim civil war / sacred-site violence",Evidence:"The Second Fitna is well documented in Muslim chronicles; details of responsibility for particular damage vary."},sourceStatus:"The Second Fitna is well documented in Muslim chronicles; details of responsibility for particular damage vary.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:685,depth:3410,title:"Mukhtar revolt invokes Husayn's cause",location:"Kufa",story:"Al-Mukhtar al-Thaqafi seized Kufa and mobilized supporters in the name of Muhammad ibn al-Hanafiyya while seeking vengeance for Husayn's death at Karbala.",context:"Early Shia political mobilization",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Early Shia political mobilization",Evidence:"The revolt is historical and important to the development of pro-Alid political identity, though it should not be equated directly with later Twelver Shiism."},sourceStatus:"The revolt is historical and important to the development of pro-Alid political identity, though it should not be equated directly with later Twelver Shiism.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:691,depth:3580,title:"Dome of the Rock completed",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:692,depth:3750,title:"Umayyads defeat Ibn al-Zubayr at Mecca",location:"Mecca",story:"Umayyad forces defeated and killed Abd Allah ibn al-Zubayr, ending the Second Fitna and restoring Umayyad control over most of the caliphate.",context:"Civil war / Umayyad consolidation",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Civil war / Umayyad consolidation",Evidence:"The event is well established in early Islamic historiography."},sourceStatus:"The event is well established in early Islamic historiography.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:705,depth:3920,title:"Umayyad expansion reaches a new phase",location:"North Africa, Central Asia and South Asia",story:"Under al-Walid I and his commanders, Umayyad armies expanded in North Africa, Transoxiana and the Indus region, helping create an empire stretching across three continents.",context:"Imperial expansion",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Imperial expansion",Evidence:"The campaigns are historically documented, but conquest did not mean immediate mass conversion; Islamization unfolded over centuries and varied by region."},sourceStatus:"The campaigns are historically documented, but conquest did not mean immediate mass conversion; Islamization unfolded over centuries and varied by region.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:711,depth:4090,title:"Muslim conquest of Iberia begins",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:717,depth:4260,title:"Second Arab siege of Constantinople fails",location:"Constantinople",story:"A major Umayyad land-and-sea campaign failed to capture the Byzantine capital, limiting further Umayyad expansion into southeastern Europe.",context:"War / Christian-Muslim overlap",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"War / Christian-Muslim overlap",Evidence:"The siege is documented in Byzantine and Islamic traditions; exact army and casualty figures are uncertain."},sourceStatus:"The siege is documented in Byzantine and Islamic traditions; exact army and casualty figures are uncertain.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:740,depth:4430,title:"Great Berber Revolt challenges Umayyad rule",location:"North Africa",story:"Berber Muslim forces rebelled against Umayyad governors, driven by taxation, political inequality and Kharijite ideas. The revolt permanently weakened direct Umayyad control in the far west.",context:"Revolt / intra-Muslim conflict",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Revolt / intra-Muslim conflict",Evidence:"The revolt was led largely by Muslims and shows that early imperial conflicts cannot be reduced to Muslim-versus-non-Muslim categories."},sourceStatus:"The revolt was led largely by Muslims and shows that early imperial conflicts cannot be reduced to Muslim-versus-non-Muslim categories.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:750,depth:4600,title:"Abbasid Revolution",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:756,depth:4770,title:"Umayyad emirate established in Cordoba",location:"Al-Andalus",story:"Abd al-Rahman I, an Umayyad survivor of the Abbasid revolution, established an independent emirate in Iberia.",context:"Dynastic state formation",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Dynastic state formation",Evidence:"The Cordoban emirate is extensively documented and developed separately from Abbasid political rule."},sourceStatus:"The Cordoban emirate is extensively documented and developed separately from Abbasid political rule.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:762,depth:4940,title:"Baghdad founded",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:833,depth:5110,title:"Mihna begins under Abbasid caliph al-Ma'mun",location:"Abbasid Caliphate",story:"The Abbasid government imposed a theological test concerning whether the Qur'an was created, pressuring scholars and officials to accept the caliph's doctrinal position.",context:"Intra-Muslim religious coercion",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Intra-Muslim religious coercion",Evidence:"The Mihna is well documented. It illustrates a struggle over religious authority between the caliphal state and scholars rather than a simple Sunni-Shia conflict."},sourceStatus:"The Mihna is well documented. It illustrates a struggle over religious authority between the caliphal state and scholars rather than a simple Sunni-Shia conflict.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:850,depth:5280,title:"Al-Mutawakkil destroys Husayn's shrine at Karbala",location:"Karbala",story:"Abbasid caliph al-Mutawakkil ordered Husayn's tomb and surrounding structures destroyed and restricted pilgrimage, part of a strongly anti-Alid policy.",context:"Sunni-Shia repression",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Sunni-Shia repression",Evidence:"Encyclopaedia Iranica records the destruction in 850–851 and the prohibition of visitation; the shrine was rebuilt after al-Mutawakkil's death."},sourceStatus:"Encyclopaedia Iranica records the destruction in 850–851 and the prohibition of visitation; the shrine was rebuilt after al-Mutawakkil's death.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:909,depth:5450,title:"Fatimid Caliphate established",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:945,depth:5620,title:"Buyids take Baghdad",location:"Baghdad",story:"The Shia Buyid dynasty took political control of Baghdad while retaining the Sunni Abbasid caliph as a figure of religious legitimacy.",context:"Dynastic change / Sunni-Shia politics",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Dynastic change / Sunni-Shia politics",Evidence:"The Buyid takeover is well documented and demonstrates the separation of caliphal religious prestige from effective political power."},sourceStatus:"The Buyid takeover is well documented and demonstrates the separation of caliphal religious prestige from effective political power.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1009,depth:5790,title:"Al-Hakim orders destruction of Holy Sepulchre",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1055,depth:5960,title:"Seljuks enter Baghdad",location:"Baghdad",story:"The Sunni Seljuk ruler Tughril Beg entered Baghdad, ending Buyid dominance and becoming military protector of the Abbasid caliphate.",context:"Dynastic change / Sunni politics",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Dynastic change / Sunni politics",Evidence:"The Seljuk takeover is well documented; the Abbasid caliph retained religious prestige while political authority remained limited."},sourceStatus:"The Seljuk takeover is well documented; the Abbasid caliph retained religious prestige while political authority remained limited.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1067,depth:6130,title:"Nizamiyya madrasa founded in Baghdad",location:"Baghdad",story:"Vizier Nizam al-Mulk founded the Nizamiyya, an influential institution supporting Sunni scholarship and state-linked education under Seljuk patronage.",context:"Religious institution / Sunni consolidation",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Religious institution / Sunni consolidation",Evidence:"The institution is well documented and belongs to a broader network of madrasas rather than the invention of Islamic higher education."},sourceStatus:"The institution is well documented and belongs to a broader network of madrasas rather than the invention of Islamic higher education.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1071,depth:6300,title:"Battle of Manzikert",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1099,depth:6470,title:"Crusaders capture Jerusalem",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1171,depth:6640,title:"Saladin ends Fatimid Caliphate in Egypt",location:"Egypt",story:"Saladin abolished the Ismaili Shia Fatimid caliphate and restored formal allegiance to the Sunni Abbasid caliph, beginning Ayyubid rule in Egypt.",context:"Sunni-Shia political transition",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Sunni-Shia political transition",Evidence:"The transition is historical and combined dynastic, military and religious change."},sourceStatus:"The transition is historical and combined dynastic, military and religious change.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1187,depth:6810,title:"Saladin recovers Jerusalem",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1206,depth:6980,title:"Delhi Sultanate established",location:"North India",story:"Qutb al-Din Aibak established a durable Muslim-ruled sultanate in northern India after the Ghurid conquests.",context:"State formation / South Asian Islam",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"State formation / South Asian Islam",Evidence:"The Delhi Sultanate comprised several dynasties and ruled religiously diverse populations; conquest and Islamization were distinct historical processes."},sourceStatus:"The Delhi Sultanate comprised several dynasties and ruled religiously diverse populations; conquest and Islamization were distinct historical processes.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1258,depth:7150,title:"Mongol sack of Baghdad",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1291,depth:7320,title:"Mamluks capture Acre",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1402,depth:7490,title:"Timur defeats Ottomans at Ankara",location:"Ankara",story:"Timur's army defeated and captured Ottoman sultan Bayezid I, triggering an Ottoman succession struggle and temporarily reversing Ottoman expansion.",context:"Inter-Muslim imperial war",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Inter-Muslim imperial war",Evidence:"The battle is firmly documented and is a clear example of major warfare between Muslim-ruled empires."},sourceStatus:"The battle is firmly documented and is a clear example of major warfare between Muslim-ruled empires.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1453,depth:7660,title:"Ottoman conquest of Constantinople",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1492,depth:7830,title:"Fall of Granada",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1501,depth:8000,title:"Safavid state makes Twelver Shiism central to Iran",location:"Iran",story:"Shah Ismail I established Safavid rule and promoted Twelver Shiism as the state creed, transforming Iran's religious landscape and sharpening rivalry with Sunni neighbors.",context:"Shia state formation",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Shia state formation",Evidence:"Iran had previously been predominantly Sunni with important Shia communities; conversion and institutional transformation unfolded over generations and involved both patronage and coercion."},sourceStatus:"Iran had previously been predominantly Sunni with important Shia communities; conversion and institutional transformation unfolded over generations and involved both patronage and coercion.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1514,depth:8170,title:"Battle of Chaldiran",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1517,depth:8340,title:"Ottomans conquer Mamluk Egypt",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1529,depth:8510,title:"First Ottoman siege of Vienna",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1571,depth:8680,title:"Battle of Lepanto",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1683,depth:8850,title:"Second Ottoman siege of Vienna",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1798,depth:9020,title:"Napoleon invades Egypt",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1801,depth:9190,title:"Wahhabi-Saudi forces sack Karbala",location:"Karbala",story:"Forces from the first Saudi-Wahhabi state attacked Karbala, looted Husayn's shrine and killed thousands, targeting practices they condemned as polytheistic.",context:"Sunni-Shia sectarian violence",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Sunni-Shia sectarian violence",Evidence:"Encyclopaedia Iranica records the 1801 attack and gives a contemporary historical estimate of about 5,000 killed; such historical casualty figures remain approximate."},sourceStatus:"Encyclopaedia Iranica records the 1801 attack and gives a contemporary historical estimate of about 5,000 killed; such historical casualty figures remain approximate.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1803,depth:9360,title:"Saudi-Wahhabi forces take Mecca",location:"Mecca",story:"Forces of the first Saudi state captured Mecca during their expansion across Arabia and imposed reformist religious practices opposed by the Ottoman order.",context:"State expansion / religious reform conflict",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"State expansion / religious reform conflict",Evidence:"The conquest was part of a political-military struggle as well as a movement of religious reform."},sourceStatus:"The conquest was part of a political-military struggle as well as a movement of religious reform.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1826,depth:9530,title:"Ottoman abolition of the Janissaries",location:"Istanbul",story:"Sultan Mahmud II destroyed the Janissary corps in the 'Auspicious Incident,' using military force to eliminate an institution that had become a major political obstacle to centralizing reform.",context:"Ottoman internal conflict / reform",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Ottoman internal conflict / reform",Evidence:"The event was an intra-Muslim state conflict tied to military modernization, not a sectarian war."},sourceStatus:"The event was an intra-Muslim state conflict tied to military modernization, not a sectarian war.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1830,depth:9700,title:"French conquest of Algeria begins",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1881,depth:9870,title:"Mahdist movement begins in Sudan",location:"Sudan",story:"Muhammad Ahmad proclaimed himself the Mahdi and led a religious-political revolt against Turco-Egyptian rule, creating a state that later fought British-led forces.",context:"Islamic revival / anti-imperial revolt",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Islamic revival / anti-imperial revolt",Evidence:"The Mahdist movement combined religious claims, local grievances and resistance to imperial rule."},sourceStatus:"The Mahdist movement combined religious claims, local grievances and resistance to imperial rule.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1898,depth:10040,title:"Battle of Omdurman ends Mahdist state",location:"Sudan",story:"Anglo-Egyptian forces defeated the Mahdist army near Omdurman, establishing a new colonial order in Sudan.",context:"Colonial war / Muslim resistance",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Colonial war / Muslim resistance",Evidence:"The battle reflected enormous technological asymmetry and ended the Mahdist state's effective independence."},sourceStatus:"The battle reflected enormous technological asymmetry and ended the Mahdist state's effective independence.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1914,depth:10210,title:"Ottoman Empire enters World War I",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1915,depth:10380,title:"Armenian genocide under Ottoman wartime rule",location:"Ottoman Empire",story:"Ottoman authorities deported and killed Armenians on a mass scale during World War I; Assyrian and Greek Christian communities also suffered mass violence in the late Ottoman wartime environment.",context:"Genocide / Christian-Muslim historical overlap",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Genocide / Christian-Muslim historical overlap",Evidence:"The Armenian genocide was carried out by the Ottoman state and associated forces in a wartime nationalist and imperial context. It must not be generalized to Muslims collectively; Muslims also rescued Armenians in some places."},sourceStatus:"The Armenian genocide was carried out by the Ottoman state and associated forces in a wartime nationalist and imperial context. It must not be generalized to Muslims collectively; Muslims also rescued Armenians in some places.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1917,depth:10550,title:"British capture Jerusalem",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1924,depth:10720,title:"Abolition of Ottoman Caliphate",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1928,depth:10890,title:"Muslim Brotherhood founded",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1932,depth:11060,title:"Saudi Arabia proclaimed",location:"Arabian Peninsula",story:"Abdulaziz Ibn Saud unified his conquests as the Kingdom of Saudi Arabia, linking dynastic rule with a longstanding alliance with Wahhabi religious institutions.",context:"State formation / Sunni religious politics",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"State formation / Sunni religious politics",Evidence:"The kingdom's political-religious system developed from the Saudi-Wahhabi alliance but changed substantially across the twentieth and twenty-first centuries."},sourceStatus:"The kingdom's political-religious system developed from the Saudi-Wahhabi alliance but changed substantially across the twentieth and twenty-first centuries.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1947,depth:11230,title:"Partition of India creates Pakistan",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1948,depth:11400,title:"Arab-Israeli war and Palestinian Nakba",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1952,depth:11570,title:"Egyptian revolution ends monarchy",location:"Egypt",story:"The Free Officers overthrew King Farouk. Under Gamal Abdel Nasser, the new regime promoted Arab nationalism and later suppressed the Muslim Brotherhood.",context:"Nationalist revolution / Islamism-state conflict",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Nationalist revolution / Islamism-state conflict",Evidence:"The revolution was led by military nationalists rather than an Islamist movement; subsequent conflict with the Brotherhood shaped modern political Islam."},sourceStatus:"The revolution was led by military nationalists rather than an Islamist movement; subsequent conflict with the Brotherhood shaped modern political Islam.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1967,depth:11740,title:"Six-Day War and Jerusalem holy sites",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1977,depth:11910,title:"Shia pilgrimage protests confront Baathist Iraq",location:"Karbala and Najaf",story:"Iraqi Shia pilgrims and activists clashed with Baathist authorities during Ashura observances amid growing repression of Shia religious institutions.",context:"Shia repression / authoritarian conflict",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Shia repression / authoritarian conflict",Evidence:"The Baath government was formally secular; repression mixed authoritarian state control with political exclusion and sectarian effects."},sourceStatus:"The Baath government was formally secular; repression mixed authoritarian state control with political exclusion and sectarian effects.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1979,depth:12080,title:"Iranian Revolution",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1979,depth:12250,title:"Grand Mosque seizure in Mecca",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1979,depth:12420,title:"Soviet invasion of Afghanistan",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1980,depth:12590,title:"Iran-Iraq War begins",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1987,depth:12760,title:"First Intifada",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1988,depth:12930,title:"Hamas founded",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:1991,depth:13100,title:"Iraqi Shia uprising after Gulf War",location:"Southern Iraq",story:"After Iraq's defeat in the Gulf War, uprisings spread through Shia-majority southern cities including Karbala and Najaf. Saddam Hussein's government crushed them with heavy violence.",context:"Uprising / state repression",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Uprising / state repression",Evidence:"The uprising had political and sectarian dimensions; Iranica notes severe casualties and destruction in Karbala, including damage around Husayn's shrine."},sourceStatus:"The uprising had political and sectarian dimensions; Iranica notes severe casualties and destruction in Karbala, including damage around Husayn's shrine.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1992,depth:13270,title:"Bosnian War targets Bosniak Muslim communities",location:"Bosnia and Herzegovina",story:"Bosnia's war followed Yugoslavia's breakup and involved Bosniak, Serb and Croat forces. Ethnic cleansing and mass atrocities disproportionately struck Bosniak Muslim civilians.",context:"Ethno-national war / anti-Muslim mass violence",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Ethno-national war / anti-Muslim mass violence",Evidence:"USHMM estimates about 100,000 killed in the war and reports that roughly 80 percent of civilians killed were Bosniaks; crimes were also committed by Bosniak and Croat forces."},sourceStatus:"USHMM estimates about 100,000 killed in the war and reports that roughly 80 percent of civilians killed were Bosniaks; crimes were also committed by Bosniak and Croat forces.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1995,depth:13440,title:"Srebrenica genocide",location:"Srebrenica, Bosnia and Herzegovina",story:"Bosnian Serb forces systematically killed around 8,000 Bosniak Muslim men and boys after capturing the UN-designated safe area of Srebrenica.",context:"Genocide / anti-Muslim mass violence",aftermath:"This event is presented within its political, social and religious setting; responsibility is assigned to the specific rulers, states, armies or movements involved rather than to Muslims as a whole.",stats:{Type:"Genocide / anti-Muslim mass violence",Evidence:"International courts determined that genocide occurred at Srebrenica. The victims were targeted as Bosniaks in an ethno-national conflict in which Muslim identity was an important component of group identity."},sourceStatus:"International courts determined that genocide occurred at Srebrenica. The victims were targeted as Bosniaks in an ethno-national conflict in which Muslim identity was an important component of group identity.",sources:[{label:"Institutional / scholarly reference",url:"https://www.metmuseum.org/toah/"}]},
  {year:1996,depth:13610,title:"Taliban capture Kabul",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2001,depth:13780,title:"September 11 attacks",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2001,depth:13950,title:"U.S.-led war in Afghanistan",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2003,depth:14120,title:"Iraq War and sectarian breakdown",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2006,depth:14290,title:"Samarra shrine bombing",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2011,depth:14460,title:"Arab uprisings",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2011,depth:14630,title:"Syrian civil war begins",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2014,depth:14800,title:"ISIS declares a caliphate",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2014,depth:14970,title:"ISIS attacks Yazidis at Sinjar",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2015,depth:15140,title:"ISIS murders 21 Coptic Christians in Libya",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2019,depth:15310,title:"ISIS territorial caliphate collapses",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2021,depth:15480,title:"Taliban return to power",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2023,depth:15650,title:"October 7 attack and Gaza war",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2024,depth:15820,title:"Gaza war and regional escalation",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2025,depth:15990,title:"Contemporary Muslim world",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]},
  {year:2026,depth:16160,title:"2026 — YOU ARE HERE",location:"",story:"Foundation entry for the Islam timeline. This event will be expanded with event-specific historical detail and sourcing during the next research pass.",context:"Islamic history",aftermath:"The timeline distinguishes Islam as a religion from the actions of specific rulers, states, armies, sectarian factions and militant movements.",stats:{Type:"Islamic history",Evidence:"Foundation entry — precision sourcing in progress."},sourceStatus:"Foundation entry — precision sourcing in progress.",sources:[{label:"Encyclopaedia Britannica — Islam",url:"https://www.britannica.com/topic/Islam"}]}
];
const eras=[{name:"Muhammad & Origins of Islam",range:"c. 570–632 CE",start:180,end:1370},{name:"Rashidun, Fitnas & Umayyads",range:"632–750 CE",start:1370,end:4600},{name:"Abbasid & Medieval Islamic World",range:"750–1099 CE",start:4600,end:6470},{name:"Crusades, Sultanates & Mongols",range:"1099–1453 CE",start:6470,end:7660},{name:"Ottoman, Safavid & Early Modern Era",range:"1453–1798 CE",start:7660,end:9020},{name:"Colonialism & Reform",range:"1798–1914 CE",start:9020,end:10210},{name:"World Wars & Post-Ottoman Order",range:"1914–1979 CE",start:10210,end:12080},{name:"Islamism & Regional Wars",range:"1979–2001 CE",start:12080,end:13780},{name:"Contemporary Era",range:"2001–2026 CE",start:13780,end:16680}];
const MAX_DEPTH=16680;
const islamJewishOverlapTitles=new Set(["Battle of the Trench and Banu Qurayza episode","Muslim capture of Jerusalem","Dome of the Rock completed","Crusaders capture Jerusalem","Arab-Israeli war and Palestinian Nakba","Six-Day War and Jerusalem holy sites","First Intifada","Hamas founded","October 7 attack and Gaza war","Gaza war and regional escalation"]);
const islamChristianOverlapTitles=new Set(["Battle of Yarmouk","Muslim capture of Jerusalem","Dome of the Rock completed","Muslim conquest of Iberia begins","Al-Hakim orders destruction of Holy Sepulchre","Battle of Manzikert","Crusaders capture Jerusalem","Saladin recovers Jerusalem","Mamluks capture Acre","Ottoman conquest of Constantinople","Fall of Granada","First Ottoman siege of Vienna","Battle of Lepanto","Second Ottoman siege of Vienna","Ottoman Empire enters World War I","British capture Jerusalem","Six-Day War and Jerusalem holy sites","ISIS murders 21 Coptic Christians in Libya"]);
let depth=0, velocity=0, paused=false, rafId=0;
const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const abyss=document.getElementById("abyss");
const person=document.getElementById("fallingPerson");
const eventsLayer=document.getElementById("eventsLayer");
const yearReadout=document.getElementById("yearReadout");
const eraReadout=document.getElementById("eraReadout");
const eraRange=document.getElementById("eraRange");
const eraLayer=document.getElementById("eraLayer");
const depthReadout=document.getElementById("depthReadout");
const progressFill=document.getElementById("progressFill");
const speedLines=document.getElementById("speedLines");
const fallTrail=document.getElementById("fallTrail");
const rockLeft=document.querySelector(".rock-left");
const rockRight=document.querySelector(".rock-right");
const rockFarLeft=document.querySelector(".rock-far-left");
const rockFarRight=document.querySelector(".rock-far-right");
const rockMidLeft=document.querySelector(".rock-mid-left");
const rockMidRight=document.querySelector(".rock-mid-right");
const bottomMarker=document.getElementById("bottomMarker");
const skyOpening=document.querySelector(".sky-opening");
const lightShaft=document.querySelector(".light-shaft");
const mist1=document.querySelector(".mist-1");
const mist2=document.querySelector(".mist-2");
const panel=document.getElementById("eventPanel");
const aboutPanel=document.getElementById("aboutPanel");

function makeParticles(){
  const wrap=document.getElementById("particles");
  for(let i=0;i<46;i++){
    const s=document.createElement("span");
    s.style.left=(8+Math.random()*84)+"%";
    s.style.top=(Math.random()*100)+"%";
    s.style.opacity=(.08+Math.random()*.25).toFixed(2);
    s.style.transform="scale("+(0.6+Math.random()*1.5)+")";
    wrap.appendChild(s);
  }
}
function yearAt(d){
  const points=[{depth:0,year:570},...events.map(e=>({depth:e.depth,year:e.year})),{depth:MAX_DEPTH,year:2026}];
  let a=points[0],b=points[1];
  for(let i=1;i<points.length;i++){
    if(d<=points[i].depth){b=points[i];a=points[i-1];break}
  }
  const span=Math.max(1,b.depth-a.depth);
  const t=Math.max(0,Math.min(1,(d-a.depth)/span));
  return Math.round(a.year+(b.year-a.year)*t);
}
function currentEraAt(d){
  return eras.find(era=>d>=era.start&&d<era.end)||eras[eras.length-1];
}
const eraEls=eras.map((era,index)=>{
  const el=document.createElement("div");
  el.className="era-transition";
  el.innerHTML='<span class="era-kicker">Entering historical era</span><strong>'+era.name+'</strong><small>'+era.range+'</small>';
  eraLayer.appendChild(el);
  return el;
});
function renderEras(){
  const center=abyss.clientHeight/2;
  const active=currentEraAt(depth);
  eraReadout.textContent=active.name;
  eraRange.textContent=active.range;
  eras.forEach((era,index)=>{
    const boundary=index===0?0:era.start;
    const y=center+(boundary-depth);
    const el=eraEls[index];
    el.style.top=y+"px";
    const distance=Math.abs(y-center);
    el.style.opacity=(y>-100&&y<abyss.clientHeight+100)?Math.max(.12,1-distance/(abyss.clientHeight*.7)):0;
  });
}
const jewishOverlapTitles=new Set(["Birth of Jesus (Yeshua)","Crucifixion of Jesus","Emergence of the early Christian movement","Council of Jerusalem and the Jewish–Gentile question","Destruction of Jerusalem reshapes Jewish and Christian communities","First Crusade massacres of Jewish communities","Crusaders capture Jerusalem","Fourth Lateran Council regulates Christian society and minorities","Spanish Inquisition established","Expulsion of Jews from Spain under Catholic monarchs","Forced conversion of Jews in Portugal","Nazi persecution of churches and Christian opponents during World War II","Ustaša persecution and Jasenovac camp end with World War II","Martyrdom of Stephen in the New Testament tradition","Execution of James son of Zebedee in Acts","Death of James, brother of Jesus","Visigothic monarchy adopts Catholic Christianity","Expulsion of Jews from Christian England","Black Death persecutions of Jews in Christian Europe","Anti-Jewish massacres and forced conversions in Iberia","Bar Kokhba revolt accelerates Jewish–Christian separation","Norwich blood-libel accusation","Fulda blood-libel accusations and killings","Martin Luther publishes On the Jews and Their Lies","German churches confront accommodation and resistance under Nazism","Christian rescuers and church networks aid Jews during the Holocaust","Seelisberg conference confronts Christian antisemitism after Holocaust","Second Vatican Council begins","Nostra Aetate rejects collective Jewish guilt","Vatican publishes We Remember: A Reflection on the Shoah","Third Council of Toledo links Visigothic monarchy and Catholic Church","Visigothic forced-baptism policy against Jews","Seventeenth Council of Toledo imposes extreme measures on Jews","York massacre of Jews","French crown expels Jews","Vienna Gesera destroys Austrian Jewish communities","Spanish Inquisition begins operating against suspected crypto-Judaism","Russian pogrom wave unfolds in predominantly Christian empire","Anti-Jewish violence erupts at Richard I's coronation","Strasbourg massacre during Black Death persecutions","Balfour Declaration creates new Christian-Jewish political intersection","Dutch churches publicly protest deportation of Jews","Bulgarian Orthodox leaders oppose deportation of Bulgarian Jews","Creation of Israel transforms ancient Christian communities in the Holy Land","Gaza war devastates historic Palestinian Christian community","Gaza and regional war continue to affect Christian holy sites and communities"]);
const markerEls=events.map((event,index)=>{
  const btn=document.createElement("button");
  btn.type="button";
  btn.className="event-marker"+(islamJewishOverlapTitles.has(event.title)?" jewish-overlap":"")+(islamChristianOverlapTitles.has(event.title)?" christian-overlap":"");
  btn.setAttribute("aria-label",event.year+" — "+event.title+". Open event details.");
  if(index%2===0) btn.style.left="7%"; else btn.style.right="7%";
  btn.innerHTML='<span class="dot"></span><span><small>'+event.year+'</small>'+(islamJewishOverlapTitles.has(event.title)?'<em class="overlap-badge">Jewish history overlap</em>':'')+(islamChristianOverlapTitles.has(event.title)?'<em class="overlap-badge christian-overlap-badge">Christian history overlap</em>':'')+'<strong>'+event.title+'</strong></span>';
  btn.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();openEvent(event)});
  eventsLayer.appendChild(btn);
  return btn;
});
function renderEvents(){
  const center=abyss.clientHeight/2;
  events.forEach((event,index)=>{
    const y=center+(event.depth-depth);
    const btn=markerEls[index];
    btn.style.top=(y-30)+"px";
    btn.style.display=(y<-120||y>abyss.clientHeight+120)?"none":"grid";
  });
}
function render(){
  const pct=Math.round((depth/MAX_DEPTH)*100);
  const currentYear=yearAt(depth);
  yearReadout.textContent=currentYear<0?Math.abs(currentYear)+" BCE":currentYear+" CE";
  depthReadout.textContent=pct+"%";
  progressFill.style.height=pct+"%";

  const speed=Math.min(1,Math.abs(velocity)/105);
  speedLines.style.opacity=(speed*.85).toFixed(2);
  fallTrail.style.opacity=(.12+speed*.5).toFixed(2);

  const direction=velocity>=0?1:-1;
  const rotate=Math.sin(depth/360)*8+(direction*speed*5);
  const bob=Math.sin(depth/105)*5;
  const depthT=pct/100;
  const perspectiveScale=(1.02-depthT*.28)+speed*.025;
  person.style.transform='translate(-50%,calc(-50% + '+bob+'px)) rotate('+rotate+'deg) scale('+perspectiveScale+')';
  person.style.opacity=Math.max(.72,1-depthT*.18);

  const wallSway=Math.sin(depth/420)*5;
  rockLeft.style.transform='translate3d('+(-wallSway)+'px,'+((depth%760)*-.24)+'px,35px) scale(1.035)';
  rockRight.style.transform='translate3d('+wallSway+'px,'+((depth%820)*-.22)+'px,35px) scale(1.035)';
  rockMidLeft.style.transform='translate3d('+(-wallSway*.55)+'px,'+((depth%980)*-.13)+'px,0) scale(1.015)';
  rockMidRight.style.transform='translate3d('+(wallSway*.55)+'px,'+((depth%1040)*-.12)+'px,0) scale(1.015)';
  rockFarLeft.style.transform='translate3d(0,'+((depth%1300)*-.07)+'px,-50px)';
  rockFarRight.style.transform='translate3d(0,'+((depth%1380)*-.065)+'px,-50px)';
  mist1.style.transform='translateY('+((depth%900)*-.23)+'px)';
  mist2.style.transform='translateY('+((depth%1100)*-.18)+'px)';

  const openingScale=Math.max(.16,1-depthT*.82);
  const openingOpacity=Math.max(.08,.9-depthT*.82);
  skyOpening.style.transform='translateX(-50%) scale('+openingScale+')';
  skyOpening.style.opacity=openingOpacity;
  skyOpening.style.filter='blur('+(5+depthT*8)+'px)';
  lightShaft.style.transform='translateX(-50%) scaleX('+(1-depthT*.45)+') scaleY('+(1-depthT*.6)+')';
  lightShaft.style.opacity=Math.max(.03,.58-depthT*.52);
  abyss.style.background=
    'radial-gradient(ellipse at 50% 0%,rgba(150,190,210,'+(0.17*(1-depthT))+'),transparent '+(25-depthT*13)+'%),'+
    'linear-gradient(180deg,#'+(depthT<.45?'17191d':'0c0d10')+' 0%,#08090b 30%,#030405 64%,#000 100%)';

  bottomMarker.classList.toggle("visible",pct>=94);
  document.querySelectorAll(".particles span").forEach((p,i)=>{
    const drift=((depth*(.04+(i%5)*.009))%(abyss.clientHeight+80));
    p.style.transform='translateY('+(-drift)+'px) translateX('+(Math.sin((depth+i*31)/130)*8)+'px)';
  });
  renderEras();
  renderEvents();
}
function tick(){
  if(!paused&&!reduced){
    depth=Math.max(0,Math.min(MAX_DEPTH,depth+velocity));
    velocity*=.84;
    if(Math.abs(velocity)<.05)velocity=0;
  }
  render();
  rafId=requestAnimationFrame(tick);
}
function descend(delta){
  if(paused)return;
  const scaled=Math.max(-260,Math.min(260,delta));
  depth=Math.max(0,Math.min(MAX_DEPTH,depth+scaled*.72));
  velocity=Math.max(-115,Math.min(115,velocity+scaled*.037));
}
function openEvent(event){
  paused=true;velocity=0;
  document.getElementById("eventDate").innerHTML=event.year+(islamJewishOverlapTitles.has(event.title)?' <span class="overlap-badge panel-overlap-badge">Jewish history overlap</span>':'')+(islamChristianOverlapTitles.has(event.title)?' <span class="overlap-badge christian-overlap-badge panel-overlap-badge">Christian history overlap</span>':'');
  document.getElementById("eventTitle").textContent=event.title;
  document.getElementById("eventLocation").textContent=event.location;
  document.getElementById("eventStory").textContent=event.story;
  document.getElementById("eventContext").textContent=event.context;
  document.getElementById("eventAftermath").textContent=event.aftermath;
  document.getElementById("eventSourceStatus").textContent=event.sourceStatus;
  const sourceWrap=document.getElementById("eventSources");
  sourceWrap.innerHTML="";
  (event.sources||[]).forEach(source=>{
    const a=document.createElement("a");
    a.href=source.url;a.target="_blank";a.rel="noopener noreferrer";
    let domain="";try{domain=new URL(source.url).hostname.replace(/^www\\./,"")}catch{}
    a.textContent=source.label+(domain&&!source.label.toLowerCase().includes(domain.toLowerCase())?" — "+domain:"");
    sourceWrap.appendChild(a);
  });
  if(!(event.sources||[]).length){
    const note=document.createElement("span");
    note.textContent="Source review still in progress.";
    sourceWrap.appendChild(note);
  }
  const dl=document.getElementById("eventStats");
  dl.innerHTML="";
  Object.entries(event.stats).forEach(([k,v])=>{
    const row=document.createElement("div");
    const dt=document.createElement("dt");
    const dd=document.createElement("dd");
    dt.textContent=k.replaceAll("_"," ");
    dd.textContent=v;
    row.append(dt,dd);dl.appendChild(row);
  });
  panel.classList.remove("hidden");
  document.body.classList.add("event-open");
  document.getElementById("closeEventBtn").focus();
}
function restart(){
  depth=0;velocity=0;paused=false;
  panel.classList.add("hidden");
  document.body.classList.remove("event-open");
  aboutPanel.classList.add("hidden");
  document.getElementById("intro").scrollIntoView({behavior:reduced?"auto":"smooth"});
}
abyss.addEventListener("wheel",e=>{
  const goingDown=e.deltaY>0, goingUp=e.deltaY<0;
  const atBottom=depth>=MAX_DEPTH-1, atTop=depth<=1;
  if((goingDown&&atBottom)||(goingUp&&atTop)) return;
  e.preventDefault();
  descend(e.deltaY);
},{passive:false});
let touchY=null;
abyss.addEventListener("touchstart",e=>{touchY=e.touches[0].clientY},{passive:true});
abyss.addEventListener("touchmove",e=>{if(touchY===null)return;const y=e.touches[0].clientY;descend((touchY-y)*2.2);touchY=y},{passive:true});
abyss.addEventListener("touchend",()=>touchY=null,{passive:true});
abyss.addEventListener("keydown",e=>{
  if(["ArrowDown","PageDown"," "].includes(e.key)){e.preventDefault();descend(230)}
  if(["ArrowUp","PageUp"].includes(e.key)){e.preventDefault();descend(-230)}
});
document.getElementById("beginBtn").addEventListener("click",()=>{abyss.scrollIntoView({behavior:reduced?"auto":"smooth"});abyss.focus()});
document.getElementById("restartBtn").addEventListener("click",restart);
document.getElementById("closeEventBtn").addEventListener("click",()=>{panel.classList.add("hidden");document.body.classList.remove("event-open");paused=false;abyss.focus()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!panel.classList.contains("hidden")){panel.classList.add("hidden");document.body.classList.remove("event-open");paused=false;abyss.focus()}});
document.getElementById("aboutBtn").addEventListener("click",()=>{aboutPanel.classList.remove("hidden");aboutPanel.scrollIntoView({behavior:reduced?"auto":"smooth"})});
document.getElementById("closeAboutBtn").addEventListener("click",()=>aboutPanel.classList.add("hidden"));

/* Explore timeline: search, filters and year jump */
const exploreToggle=document.getElementById("exploreToggle");
const explorePanel=document.getElementById("explorePanel");
const eventSearch=document.getElementById("eventSearch");
const eraFilter=document.getElementById("eraFilter");
const typeFilter=document.getElementById("typeFilter");
const filterResults=document.getElementById("filterResults");
const filterCount=document.getElementById("filterCount");
const yearJump=document.getElementById("yearJump");
const yearEra=document.getElementById("yearEra");

function eraForEvent(event){return eras.find(era=>event.depth>=era.start&&event.depth<era.end)||eras[eras.length-1]}
function eventType(event){return (event.stats&&event.stats.Type)||"Other"}
eras.forEach(era=>{const o=document.createElement("option");o.value=era.name;o.textContent=era.name;eraFilter.appendChild(o)});
[...new Set(events.map(eventType))].sort((a,b)=>a.localeCompare(b)).forEach(type=>{const o=document.createElement("option");o.value=type;o.textContent=type;typeFilter.appendChild(o)});

function jumpToDepth(target){
  paused=false;velocity=0;depth=Math.max(0,Math.min(MAX_DEPTH,target));render();
  abyss.scrollIntoView({behavior:reduced?"auto":"smooth",block:"center"});abyss.focus({preventScroll:true});
}
function jumpToEvent(event){jumpToDepth(event.depth)}
function applyFilters(){
  const q=eventSearch.value.trim().toLowerCase(), era=eraFilter.value, type=typeFilter.value;
  const matches=events.filter((event,index)=>{
    const hay=[event.title,event.location,event.story,eventType(event),event.year].join(" ").toLowerCase();
    const ok=(!q||hay.includes(q))&&(!era||eraForEvent(event).name===era)&&(!type||eventType(event)===type);
    markerEls[index].classList.toggle("filtered-out",!ok);
    return ok;
  });
  filterCount.textContent=matches.length+" event"+(matches.length===1?"":"s");
  filterResults.innerHTML="";
  const show=(q||era||type)?matches.slice(0,18):[];
  show.forEach(event=>{
    const b=document.createElement("button");b.type="button";b.className="filter-result";
    const y=event.year<0?Math.abs(event.year)+" BCE":event.year+" CE";
    b.innerHTML="<small>"+y+" · "+event.location+"</small><strong>"+event.title+"</strong>";
    b.addEventListener("click",()=>jumpToEvent(event));filterResults.appendChild(b);
  });
  if((q||era||type)&&!matches.length){const n=document.createElement("span");n.className="source-links";n.textContent="No matching events.";filterResults.appendChild(n)}
}
function depthForYear(year){
  const sorted=events.slice().sort((a,b)=>a.year-b.year);
  if(year<=sorted[0].year)return sorted[0].depth;
  if(year>=sorted[sorted.length-1].year)return sorted[sorted.length-1].depth;
  for(let i=1;i<sorted.length;i++){
    if(year<=sorted[i].year){
      const a=sorted[i-1],b=sorted[i],span=Math.max(1,b.year-a.year),t=(year-a.year)/span;
      return a.depth+(b.depth-a.depth)*t;
    }
  }
  return 0;
}
function doYearJump(){
  const raw=parseInt(yearJump.value,10);if(!Number.isFinite(raw)||raw<1)return;
  const y=yearEra.value==="BCE"?-raw:raw;
  jumpToDepth(depthForYear(Math.max(570,Math.min(2026,y))));
}
exploreToggle.addEventListener("click",()=>{
  const open=explorePanel.classList.contains("hidden");explorePanel.classList.toggle("hidden",!open);exploreToggle.setAttribute("aria-expanded",String(open));
  if(open)eventSearch.focus();
});
[eventSearch,eraFilter,typeFilter].forEach(el=>el.addEventListener(el.tagName==="INPUT"?"input":"change",applyFilters));
document.getElementById("yearJumpBtn").addEventListener("click",doYearJump);
yearJump.addEventListener("keydown",e=>{if(e.key==="Enter")doYearJump()});
document.getElementById("clearFilters").addEventListener("click",()=>{
  eventSearch.value="";eraFilter.value="";typeFilter.value="";yearJump.value="";yearEra.value="CE";applyFilters();
});
applyFilters();

makeParticles();render();rafId=requestAnimationFrame(tick);