(()=>{"use strict";
const yearEl=document.getElementById("yearReadout"),mapYear=document.getElementById("mapYear"),countEl=document.getElementById("mapCommunityCount"),dots=document.getElementById("mapDots"),legend=document.getElementById("mapLegend"),land=document.getElementById("mapLand");
if(!yearEl||!mapYear||!countEl||!dots||!legend||!land)return;
const periods=[{"from":570,"to":621,"c":[["Mecca",21.4,39.8,5]]},{"from":622,"to":632,"c":[["Medina",24.5,39.6,6],["Mecca",21.4,39.8,5]]},{"from":633,"to":749,"c":[["Arabia",24,44,5],["Damascus",33.5,36.3,6],["Iraq",33,44,5],["Egypt",30,31.2,4],["Levant",32,35.2,4],["Persia",32,53,4],["North Africa",34,10,3]]},{"from":750,"to":999,"c":[["Baghdad",33.3,44.4,7],["Persia",32,53,5],["Egypt",30,31.2,5],["North Africa",34,10,4],["Al-Andalus",37,-4,5],["Central Asia",40,65,3]]},{"from":1000,"to":1299,"c":[["Egypt",30,31.2,5],["Iraq",33,44,4],["Persia",32,53,5],["Al-Andalus",37,-4,4],["North Africa",34,10,4],["Anatolia",39,32.5,3],["Central Asia",40,65,4],["Indian subcontinent",28,77,3]]},{"from":1300,"to":1599,"c":[["Ottoman lands",41,29,6],["Persia",32,53,5],["Egypt",30,31.2,4],["North Africa",34,10,4],["Central Asia",40,65,4],["Indian subcontinent",28,77,5],["Southeast Asia",0,105,3]]},{"from":1600,"to":1799,"c":[["Ottoman Empire",41,29,6],["Safavid / Iranian lands",32,53,5],["Mughal India",28,77,6],["North Africa",34,10,4],["Southeast Asia",-3,110,5],["West Africa",12,-2,3]]},{"from":1800,"to":1945,"c":[["Middle East",30,45,6],["North Africa",30,10,5],["South Asia",25,75,6],["Southeast Asia",-3,110,6],["West Africa",12,-2,4],["Central Asia",42,65,4]]},{"from":1946,"to":2026,"c":[["Middle East",30,45,6],["North Africa",30,10,6],["South Asia",25,75,7],["Southeast Asia",-3,110,7],["West Africa",12,-2,6],["Central Asia",42,65,4],["Europe",50,10,3],["North America",40,-90,2]]}];
function point(lat,lon){return{x:lon+180,y:90-lat}}
function ringPath(r){return r.map((c,i)=>{const p=point(c[1],c[0]);return(i?"L":"M")+p.x.toFixed(2)+" "+p.y.toFixed(2)}).join(" ")+" Z"}
function geometryPath(g){if(g.type==="Polygon")return g.coordinates.map(ringPath).join(" ");if(g.type==="MultiPolygon")return g.coordinates.flatMap(p=>p.map(ringPath)).join(" ");return""}
fetch("data/ne_110m_land.geojson").then(r=>r.json()).then(data=>{const ns="http://www.w3.org/2000/svg",frag=document.createDocumentFragment();data.features.forEach(f=>{const d=geometryPath(f.geometry);if(!d)return;const p=document.createElementNS(ns,"path");p.setAttribute("d",d);p.setAttribute("fill-rule","evenodd");frag.appendChild(p)});land.replaceChildren(frag)}).catch(()=>{});
function parseYear(){const t=yearEl.textContent.trim();const n=parseInt(t.replace(/[^0-9]/g,""),10);return Number.isFinite(n)?(/BCE/i.test(t)?-n:n):null}
let comparisonMapActive=false;
function update(){if(comparisonMapActive)return;const y=parseYear();if(y===null)return;const p=periods.find(p=>y>=p.from&&y<=p.to)||periods[periods.length-1];mapYear.textContent=y<0?Math.abs(y)+" BCE":y+" CE";countEl.textContent=p.c.length+(p.c.length===1?" center":" centers");dots.innerHTML="";legend.innerHTML="";const ns="http://www.w3.org/2000/svg";p.c.forEach(([name,lat,lon,size])=>{const q=point(lat,lon),halo=document.createElementNS(ns,"circle"),core=document.createElementNS(ns,"circle");halo.setAttribute("cx",q.x);halo.setAttribute("cy",q.y);halo.setAttribute("r",2.2+size*.72);halo.setAttribute("class","map-community");core.setAttribute("cx",q.x);core.setAttribute("cy",q.y);core.setAttribute("r",.65+size*.28);core.setAttribute("class","map-community-core");dots.append(halo,core);const item=document.createElement("span");item.textContent=name;legend.appendChild(item)})}
new MutationObserver(update).observe(yearEl,{childList:true,characterData:true,subtree:true});
update();
window.addEventListener("history-map-compare",e=>{
 comparisonMapActive=!!(e.detail&&e.detail.active);
 if(!comparisonMapActive)update();
});
})();